import { PokemonAnalysis } from '../types';

// Helper to expand compact data into full Analysis object
const createMon = (
  id: number,
  nameEn: string,
  nameZh: string,
  types: string[],
  roleEn: string,
  roleZh: string,
  tier: string,
  stats: number[], // [HP, Atk, Def, SpA, SpD, Spe]
  keyMovesEn: string[],
  keyMovesZh: string[],
  summaryEn: string,
  summaryZh: string,
  related: string[] = []
): PokemonAnalysis => {
  return {
    nameEn, nameZh,
    types,
    roleEn, roleZh,
    tier,
    stats: { hp: stats[0], attack: stats[1], defense: stats[2], spAtk: stats[3], spDef: stats[4], speed: stats[5] },
    strengthsEn: ["Fairy types", "Steel types", "Low defense units"], 
    strengthsZh: ["妖精系", "钢系", "低耐久单位"],
    weaknessesEn: ["Ice Beam", "Earthquake", "Faster Crowd Control"],
    weaknessesZh: ["冰冻光束", "地震", "高速控制"],
    coverageEn: ["Fire", "Ground", "Ice"], 
    coverageZh: ["火", "地面", "冰"],
    movepoolEn: keyMovesEn,
    movepoolZh: keyMovesZh,
    partnersEn: ["Incineroar", "Rillaboom"],
    partnersZh: ["炽焰咆哮虎", "轰擂金刚猩"],
    matchupNetwork: [], 
    summaryEn, summaryZh,
    relatedForms: related
  };
};

export const PRELOADED_POKEMON_LIST: PokemonAnalysis[] = [
  // --- RESTRICTED LEGENDARIES (S TIER) ---
  createMon(718, "Zygarde (Complete)", "基格尔德(完全)", ["Dragon", "Ground"], "Tank / Anchor", "核心坦克 / 阵地", "S+", 
    [216, 100, 121, 91, 95, 85], 
    ["Thousand Arrows", "Dragon Dance", "Rest", "Coil", "Extreme Speed", "Glare", "Substitute", "Toxic"],
    ["千箭齐发", "龙之舞", "睡觉", "盘蜷", "神速", "大蛇瞪眼", "替身", "剧毒"],
    "The absolute raid boss of Z-A. Massive HP pool combined with Thousand Arrows hitting Flying types makes it nearly uncounterable once set up.",
    "Z-A 环境的绝对BOSS。超高的HP配合千箭齐发无视飞行系的特性，使其在强化后几乎无法被针对。",
    ["Zygarde-10", "Zygarde-50"]
  ),
  createMon(716, "Xerneas", "哲尔尼亚斯", ["Fairy"], "Geomancy Sweeper", "大地掌控推队", "S", 
    [126, 131, 95, 131, 98, 99], 
    ["Geomancy", "Moonblast", "Dazzling Gleam", "Protect", "Thunderbolt", "Focus Blast", "Substitute", "Psyshock"],
    ["大地掌控", "月亮之力", "魔法闪耀", "守住", "十万伏特", "真气弹", "替身", "精神冲击"],
    "Define the meta with Geomancy. Once it sets up, Fairy Aura boosted Moonblasts obliterate everything that doesn't resist Fairy.",
    "大地掌控定义了环境。一旦强化成功，妖精气场加持下的月亮之力将摧毁所有非抵抗单位。"
  ),
  createMon(717, "Yveltal", "伊菲尔塔尔", ["Dark", "Flying"], "Drain Tank / Priority", "吸血坦克 / 先制", "S", 
    [126, 131, 95, 131, 98, 99], 
    ["Dark Pulse", "Oblivion Wing", "Sucker Punch", "Heat Wave", "Snarl", "Foul Play", "Protect", "Tailwind"],
    ["恶之波动", "死亡之翼", "突袭", "热风", "大声咆哮", "欺诈", "守住", "顺风"],
    "Dark Aura boosts Sucker Punch to nuclear levels. Oblivion Wing provides unparalleled sustain in the Z-A action combat system.",
    "暗黑气场将突袭提升至核弹级别。死亡之翼在Z-A的动作战斗系统中提供了无与伦比的续航。"
  ),
  createMon(150, "Mega Mewtwo Y", "超级超梦Y", ["Psychic"], "Fast Special Attacker", "高速特攻手", "S", 
    [106, 150, 70, 194, 120, 140], 
    ["Psystrike", "Ice Beam", "Fire Blast", "Focus Blast", "Recover", "Calm Mind", "Shadow Ball", "Taunt"],
    ["精神击破", "冰冻光束", "大字爆炎", "真气弹", "自我再生", "冥想", "暗影球", "挑衅"],
    "Highest Special Attack in the game. With 140 Speed (High CDR), it spams AOE moves rapidly.",
    "游戏中最高的特攻种族值。配合140的速度（高冷却缩减），可以极快地倾泻AOE技能。",
    ["Mewtwo", "Mega Mewtwo X"]
  ),

  // --- MEGA EVOLUTIONS (S/A TIER) ---
  createMon(115, "Mega Kangaskhan", "超级袋兽", ["Normal"], "Parental Bond Breaker", "亲子爱破盾", "S", 
    [105, 125, 100, 60, 100, 100], 
    ["Fake Out", "Double-Edge", "Sucker Punch", "Power-Up Punch", "Low Kick", "Earthquake", "Ice Punch", "Protect"],
    ["击掌奇袭", "舍身冲撞", "突袭", "增强拳", "踢倒", "地震", "冰冻拳", "守住"],
    "Parental Bond breaks Sashes and Substitutes. Fake Out pressure is immense in doubles/squad formats.",
    "亲子爱特性完美针对气势披带和替身。击掌奇袭在双打/小队模式下压制力巨大。"
  ),
  createMon(373, "Mega Salamence", "超级暴飞龙", ["Dragon", "Flying"], "Aerial Ace", "天空之肤核心", "S", 
    [95, 145, 130, 120, 90, 120], 
    ["Double-Edge", "Dragon Dance", "Roost", "Earthquake", "Hyper Voice", "Tailwind", "Protect", "Flamethrower"],
    ["舍身冲撞", "龙之舞", "羽栖", "地震", "巨声", "顺风", "守住", "喷射火焰"],
    "Aerilate Double-Edge hits incredibly hard. Intimidate before Mega Evolving adds defensive utility.",
    "天空之肤加持下的舍身冲撞伤害惊人。Mega进化前的威吓提供了防御面的辅助。"
  ),
  createMon(94, "Mega Gengar", "超级耿鬼", ["Ghost", "Poison"], "Trapper / Assassin", "踩影抓人 / 刺客", "S", 
    [60, 65, 80, 170, 95, 130], 
    ["Shadow Ball", "Sludge Bomb", "Perish Song", "Protect", "Will-O-Wisp", "Icy Wind", "Taunt", "Destiny Bond"],
    ["暗影球", "污泥炸弹", "灭亡之歌", "守住", "鬼火", "冰冻之风", "挑衅", "同命"],
    "Shadow Tag prevents escapes, enabling guaranteed kills with Perish Song or pure damage matches.",
    "踩影特性阻止对手逃跑，配合灭亡之歌或纯伤害压制可确保稳定击杀。"
  ),
  createMon(6, "Mega Charizard Y", "超级喷火龙Y", ["Fire", "Flying"], "Sun Setter", "晴天核弹", "A+", 
    [78, 104, 78, 159, 115, 100], 
    ["Heat Wave", "Solar Beam", "Scorching Sands", "Roost", "Overheat", "Air Slash", "Protect", "Tailwind"],
    ["热风", "日光束", "热沙大地", "羽栖", "过热", "空气斩", "守住", "顺风"],
    "Drought sets Sun instantly. Heat Wave becomes a massive AOE nuke that melts non-resists.",
    "日照特性瞬间开启晴天。热风变成巨大的AOE核弹，融化所有非抵抗单位。",
    ["Charizard", "Mega Charizard X"]
  ),
  createMon(303, "Mega Mawile", "超级大嘴娃", ["Steel", "Fairy"], "Huge Power Pivot", "大力士", "A+", 
    [50, 105, 125, 55, 95, 50], 
    ["Play Rough", "Iron Head", "Sucker Punch", "Swords Dance", "Protect", "Fire Fang", "Knock Off", "Thunder Punch"],
    ["嬉闹", "铁头", "突袭", "剑舞", "守住", "雷电拳", "拍落", "冰冻拳"],
    "Huge Power doubles its attack stat, giving it the highest raw physical damage output in the game alongside great typing.",
    "大力士特性使其攻击翻倍，配合优秀的属性抗性，拥有游戏中最高的物理输出面板。"
  ),
  createMon(448, "Mega Lucario", "超级路卡利欧", ["Fighting", "Steel"], "Adaptability Sweeper", "适应力收割", "A", 
    [70, 145, 88, 140, 70, 112], 
    ["Close Combat", "Meteor Mash", "Bullet Punch", "Vacuum Wave", "Swords Dance", "Nasty Plot", "Protect", "Extreme Speed"],
    ["近身战", "彗星拳", "子弹拳", "真空波", "剑舞", "诡计", "守住", "神速"],
    "Adaptability boosts STAB moves significantly. Can run mixed sets to break any wall.",
    "适应力大幅提升本系技能伤害。双刀配置可以突破任何盾牌。"
  ),

  // --- META STAPLES (A TIER) ---
  createMon(681, "Aegislash", "坚盾剑怪", ["Steel", "Ghost"], "Stance Change Pivot", "形态切换 / 弱策", "A+", 
    [60, 50, 140, 50, 140, 60], 
    ["King's Shield", "Shadow Ball", "Flash Cannon", "Close Combat", "Shadow Sneak", "Sacred Sword", "Wide Guard", "Toxic"],
    ["王者盾牌", "暗影球", "加农光炮", "近身战", "影子偷袭", "圣剑", "广域防守", "剧毒"],
    "Unique mechanics allow it to tank hits and deal massive damage. King's Shield lowers attacker stats.",
    "独特的机制使其既能承伤又能输出。王者盾牌能降低攻击者的属性。"
  ),
  createMon(663, "Talonflame", "烈箭鹰", ["Fire", "Flying"], "Priority Tailwind", "疾风之翼 / 顺风", "A", 
    [78, 81, 71, 74, 69, 126], 
    ["Tailwind", "Brave Bird", "Flare Blitz", "Roost", "Will-O-Wisp", "Taunt", "Protect", "Quick Guard"],
    ["顺风", "勇鸟猛攻", "闪焰冲锋", "羽栖", "鬼火", "挑衅", "守住", "快速防守"],
    "Gale Wings gives priority Tailwind, ensuring speed control for the team immediately.",
    "疾风之翼提供先制顺风，确保队伍立即获得速度优势。"
  ),
  createMon(658, "Greninja (Ash)", "小智版甲贺忍蛙", ["Water", "Dark"], "Battle Bond", "羁绊变身", "A", 
    [72, 145, 67, 153, 71, 132], 
    ["Water Shuriken", "Dark Pulse", "Hydro Pump", "Ice Beam", "Gunk Shot", "U-turn", "Spikes", "Grass Knot"],
    ["飞水手里剑", "恶之波动", "水炮", "冰冻光束", "垃圾射击", "急速折返", "撒菱", "打草结"],
    "Once it secures a KO, Battle Bond triggers, boosting stats and making Water Shuriken hit hard.",
    "一旦完成击杀，羁绊变身触发，大幅提升属性并强化飞水手里剑的威力。",
    ["Greninja"]
  ),
  createMon(591, "Amoonguss", "败露球菇", ["Grass", "Poison"], "Spore Support", "愤怒粉 / 蘑菇孢子", "A", 
    [114, 85, 70, 85, 80, 30], 
    ["Spore", "Rage Powder", "Pollen Puff", "Clear Smog", "Protect", "Giga Drain", "Sludge Bomb", "Grass Knot"],
    ["蘑菇孢子", "愤怒粉", "花粉团", "清除之烟", "守住", "终极吸取", "污泥炸弹", "打草结"],
    "The ultimate disruptor. Rage Powder redirects attacks while Spore puts threats to sleep.",
    "终极干扰者。愤怒粉重定向攻击，蘑菇孢子催眠威胁目标。"
  ),
  createMon(598, "Ferrothorn", "坚果哑铃", ["Grass", "Steel"], "Iron Barbs Wall", "铁刺盾牌", "A", 
    [74, 94, 131, 54, 116, 20], 
    ["Gyro Ball", "Power Whip", "Leech Seed", "Stealth Rock", "Protect", "Iron Defense", "Body Press", "Thunder Wave"],
    ["陀螺球", "强力鞭打", "寄生种子", "隐形岩", "守住", "铁壁", "扑击", "电磁波"],
    "Walls Xerneas and Kyogre (if present). Iron Barbs punishes physical attackers heavily.",
    "完封哲尔尼亚斯。铁刺特性严厉惩罚物理攻击者。"
  ),
  createMon(445, "Garchomp", "烈咬陆鲨", ["Dragon", "Ground"], "Rough Skin Tank", "粗糙皮肤 / 鲨鱼皮", "A", 
    [108, 130, 95, 80, 85, 102], 
    ["Earthquake", "Dragon Claw", "Swords Dance", "Protect", "Rock Slide", "Iron Head", "Stomping Tantrum", "Substitute"],
    ["地震", "龙爪", "剑舞", "守住", "岩崩", "铁头", "跺脚", "替身"],
    "Excellent stats and typing. Rough Skin + Rocky Helmet chips down physical attackers quickly.",
    "优秀的种族值和属性。粗糙皮肤+凸凸头盔能迅速磨损物理攻击者。",
    ["Mega Garchomp"]
  ),
  createMon(700, "Sylveon", "仙子伊布", ["Fairy"], "Hyper Voice Spam", "妖精皮肤 / 巨声", "B+", 
    [95, 65, 65, 110, 130, 60], 
    ["Hyper Voice", "Wish", "Protect", "Mystical Fire", "Psyshock", "Calm Mind", "Shadow Ball", "Yawn"],
    ["巨声", "祈愿", "守住", "魔法火焰", "精神冲击", "冥想", "暗影球", "哈欠"],
    "Pixilate Hyper Voice goes through substitutes and deals consistent AOE damage.",
    "妖精皮肤加持的巨声可穿透替身并造成稳定的AOE伤害。"
  ),
  createMon(637, "Volcarona", "火神蛾", ["Bug", "Fire"], "Quiver Dance", "蝶舞", "B+", 
    [85, 60, 65, 135, 105, 100], 
    ["Quiver Dance", "Heat Wave", "Bug Buzz", "Giga Drain", "Protect", "Rage Powder", "Hurricane", "Will-O-Wisp"],
    ["蝶舞", "热风", "虫鸣", "终极吸取", "守住", "愤怒粉", "暴风", "鬼火"],
    "Flame Body burns physical attackers. Quiver Dance makes it a terrifying special sweeper.",
    "火焰之躯灼伤物理攻击者。蝶舞使其成为可怕的特攻推队手。"
  ),
  createMon(248, "Tyranitar", "班基拉斯", ["Rock", "Dark"], "Sand Stream", "扬沙", "B+", 
    [100, 134, 110, 95, 100, 61], 
    ["Rock Slide", "Crunch", "Low Kick", "Protect", "High Horsepower", "Stone Edge", "Heavy Slam", "Dragon Dance"],
    ["岩崩", "咬碎", "踢倒", "守住", "十万马力", "尖石攻击", "重磅冲撞", "龙之舞"],
    "Sets Sandstorm, boosting its own SpDef. Strong matchups against Ghosts and Flying types.",
    "开启沙暴，提升自身特防。对幽灵系和飞行系有极强的压制力。",
    ["Mega Tyranitar"]
  ),
  createMon(212, "Scizor", "巨钳螳螂", ["Bug", "Steel"], "Technician Bullet Punch", "技术高手 / 子弹拳", "B+", 
    [70, 130, 100, 55, 80, 65], 
    ["Bullet Punch", "U-turn", "Dual Wingbeat", "Superpower", "Swords Dance", "Protect", "Knock Off", "Bug Bite"],
    ["子弹拳", "急速折返", "双翼", "蛮力", "剑舞", "守住", "拍落", "虫咬"],
    "Technician boosted Bullet Punch cleans up weakened teams and counters Fairies.",
    "技术高手加持的子弹拳能收割残血队伍并克制妖精系。",
    ["Mega Scizor"]
  ),
  createMon(479, "Rotom-Wash", "洛托姆(清洗)", ["Electric", "Water"], "Levitate Pivot", "洗衣机 / 漂浮", "B", 
    [50, 65, 107, 105, 107, 86], 
    ["Hydro Pump", "Volt Switch", "Will-O-Wisp", "Protect", "Thunderbolt", "Nasty Plot", "Ally Switch", "Trick"],
    ["水炮", "伏特替换", "鬼火", "守住", "十万伏特", "诡计", "交换场地", "戏法"],
    "Only one weakness (Grass). Volt Switch provides momentum while Will-O-Wisp neuters physical threats.",
    "只有一个弱点（草）。伏特替换提供节奏，鬼火废掉物理威胁。"
  ),
  createMon(184, "Azumarill", "玛力露丽", ["Water", "Fairy"], "Huge Power Belly Drum", "大力士 / 腹鼓", "B", 
    [100, 50, 80, 60, 80, 50], 
    ["Aqua Jet", "Play Rough", "Liquidation", "Belly Drum", "Protect", "Superpower", "Perish Song", "Ice Spinner"],
    ["水流喷射", "嬉闹", "水流裂破", "腹鼓", "守住", "蛮力", "灭亡之歌", "冰旋"],
    "Belly Drum + Aqua Jet is a classic win condition. Fairy type helps against Dragons.",
    "腹鼓配合水流喷射是经典的致胜手段。妖精属性有助于对抗龙系。"
  ),
  createMon(707, "Klefki", "钥匙圈", ["Steel", "Fairy"], "Prankster Support", "恶作剧之心 / 钥匙圈", "B", 
    [57, 80, 91, 80, 87, 75], 
    ["Thunder Wave", "Reflect", "Light Screen", "Foul Play", "Swagger", "Magnet Rise", "Play Rough", "Spikes"],
    ["电磁波", "反射壁", "光墙", "欺诈", "虚张声势", "电磁飘浮", "嬉闹", "撒菱"],
    "Prankster Screens and Thunder Wave provide immediate team support and speed control.",
    "恶作剧之心开启双墙和电磁波，提供即时的队伍辅助和速度控制。"
  ),
  createMon(282, "Mega Gardevoir", "超级沙奈朵", ["Psychic", "Fairy"], "Pixilate Nuke", "妖精皮肤", "B+", 
    [68, 85, 65, 165, 135, 100], 
    ["Hyper Voice", "Psychic", "Trick Room", "Protect", "Shadow Ball", "Focus Blast", "Calm Mind", "Encore"],
    ["巨声", "精神强念", "戏法空间", "守住", "暗影球", "真气弹", "冥想", "再来一次"],
    "Pixilate Hyper Voice hits incredibly hard in AOE. Can also set Trick Room.",
    "妖精皮肤加持的巨声拥有恐怖的AOE伤害。也能开启戏法空间。"
  ),
  createMon(6, "Mega Charizard X", "超级喷火龙X", ["Fire", "Dragon"], "Tough Claws Dancer", "硬爪龙舞", "A", 
    [78, 130, 111, 130, 85, 100], 
    ["Flare Blitz", "Dragon Claw", "Dragon Dance", "Roost", "Thunder Punch", "Earthquake", "Will-O-Wisp", "Protect"],
    ["闪焰冲锋", "龙爪", "龙之舞", "羽栖", "雷电拳", "地震", "鬼火", "守住"],
    "Changes type to Dragon, losing Electric/Water weaknesses. Tough Claws boosts contact moves.",
    "属性变为龙系，失去电/水弱点。硬爪特性提升接触类招式威力。"
  ),
  createMon(149, "Dragonite", "快龙", ["Dragon", "Flying"], "Multiscale Weakness Policy", "多重鳞片", "B", 
    [91, 134, 95, 100, 100, 80], 
    ["Extreme Speed", "Dragon Claw", "Dragon Dance", "Roost", "Iron Head", "Stomping Tantrum", "Thunder Punch", "Ice Spinner"],
    ["神速", "龙爪", "龙之舞", "羽栖", "铁头", "跺脚", "雷电拳", "冰旋"],
    "Multiscale ensures it survives a hit to setup Dragon Dance. Extreme Speed picks off fast threats.",
    "多重鳞片确保能吃下一击并强化龙舞。神速收割高速脆皮。"
  ),
  createMon(609, "Chandelure", "水晶灯火灵", ["Ghost", "Fire"], "Flash Fire Sweeper", "引火", "B", 
    [60, 55, 90, 145, 90, 80], 
    ["Heat Wave", "Shadow Ball", "Trick Room", "Protect", "Overheat", "Energy Ball", "Imprison", "Will-O-Wisp"],
    ["热风", "暗影球", "戏法空间", "守住", "过热", "能量球", "封印", "鬼火"],
    "Huge SpAtk stat. Immune to Fire and Fighting. Great Trick Room setter or sweeper.",
    "极高的特攻。免疫火系和格斗系。优秀的戏法空间开启者或打手。"
  ),
  createMon(678, "Meowstic (Male)", "超能妙喵(雄性)", ["Psychic"], "Prankster Utility", "恶作剧之心", "B", 
    [74, 48, 76, 83, 81, 104], 
    ["Fake Out", "Psychic", "Thunder Wave", "Quick Guard", "Helping Hand", "Reflect", "Light Screen", "Skill Swap"],
    ["击掌奇袭", "精神强念", "电磁波", "快速防守", "帮助", "反射壁", "光墙", "特性互换"],
    "Male version has Prankster. Priority Quick Guard blocks opposing priority moves like Fake Out.",
    "雄性拥有恶作剧之心。先制快速防守可阻挡对手的击掌奇袭等先制技能。"
  ),
  createMon(473, "Mamoswine", "象牙猪", ["Ice", "Ground"], "Dragon Slayer", "屠龙杀手", "B", 
    [110, 130, 80, 70, 60, 80], 
    ["Icicle Crash", "Earthquake", "Ice Shard", "High Horsepower", "Protect", "Knock Off", "Rock Slide", "Freeze-Dry"],
    ["冰柱坠击", "地震", "冰砾", "十万马力", "守住", "拍落", "岩崩", "冷冻干燥"],
    "STAB Ice/Ground coverage is unresisted by most. Ice Shard picks off weakened Dragons/Flyers.",
    "本系冰/地打击面几乎无盲点。冰砾收割残血的龙系/飞行系。"
  ),
  createMon(254, "Mega Sceptile", "超级蜥蜴王", ["Grass", "Dragon"], "Lightning Rod", "避雷针", "B", 
    [70, 110, 75, 145, 85, 145], 
    ["Leaf Storm", "Dragon Pulse", "Focus Blast", "Protect", "Giga Drain", "Energy Ball", "Quick Guard", "Detect"],
    ["飞叶风暴", "龙之波动", "真气弹", "守住", "终极吸取", "能量球", "快速防守", "看穿"],
    "Lightning Rod redirects Electric attacks. Extremely fast Special Attacker.",
    "避雷针吸收电系攻击。极快的高速特攻手。"
  )
];